### ISSUE TITLE
Alternative submission limits (e.g. time-based refill)

### ISSUE THREAD

**Issue by sealexan** [mp-access/Backend-Re#11]
Instead of limiting the maximum number of submissions, we could use a time-staggered refill approach. I.e. you get 1 submission per day or per 48 hours.
This might actually have some advantage, since the students will be compelled to re-visit the exercises more often. This could have a reinforcing effect on learning, while at the same time reducing the number of complaints of students who just shoot through their submissions without a good solution.

**Comment by ofvalentine** [comment]
Closed with 6ca22804de047a2565e640d8f41c9b1b7d178900
