### ISSUE TITLE
Integrate SwitchAAI (Shibboleth) Login

### ISSUE THREAD

**Issue by sealexan** [mp-access/Backend-Re#3]
Students should be able to log in using their SwitchAAI Login. Keycloak should still be used for user management, only the login should be delegated.
Maybe [https://github.com/vs-eth/keycloakshibd](https://github.com/vs-eth/keycloakshibd) can help.

**Comment by ofvalentine** [comment]
Closed in ad9eac966fbb233104d381cd36b255c78bd8bd49
